CREATE TABLE IF NOT EXISTS `order_payments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `provider` varchar(32) NOT NULL DEFAULT 'vtb_sbp',
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `amount` decimal(12,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'RUB',
  `order_number` varchar(36) NOT NULL,
  `vtb_md_order` varchar(36),
  `vtb_form_url` text,
  `vtb_qr_id` varchar(128),
  `vtb_qr_payload` text,
  `vtb_qr_image` longtext,
  `vtb_qr_status` varchar(64),
  `vtb_transaction_state` varchar(64),
  `vtb_error_code` varchar(16),
  `vtb_error_message` text,
  `vtb_register_response` longtext,
  `vtb_qr_response` longtext,
  `vtb_status_response` longtext,
  `expires_at` timestamp NULL,
  `paid_at` timestamp NULL,
  `last_checked_at` timestamp NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_payments_order_number_unique` (`order_number`),
  KEY `order_payments_order_id_idx` (`order_id`),
  KEY `order_payments_status_provider_idx` (`status`, `provider`),
  KEY `order_payments_vtb_md_order_idx` (`vtb_md_order`),
  KEY `order_payments_vtb_qr_id_idx` (`vtb_qr_id`),
  CONSTRAINT `order_payments_order_id_fk`
    FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
);
